[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
signedvoting = "EF5j7v44KDGfagMWfB9bNDyyvuVjWNwhCc5cdJFkYKdv"

[programs.devnet]
signedvoting = "EF5j7v44KDGfagMWfB9bNDyyvuVjWNwhCc5cdJFkYKdv"

[programs.mainnet]
signedvoting = "EF5j7v44KDGfagMWfB9bNDyyvuVjWNwhCc5cdJFkYKdv"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npm run test"
